name: CI
on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Tests
        run: bash ./gradlew test --stacktrace
      - name: Build Signed APK
        uses: victorbnl/build-signed-apk@main
        with:
          keystore: ${{ secrets.SIGNING_KEY }}
          keystore_password: ${{ secrets.KEY_STORE_PASSWORD }}
          key_alias: ${{ secrets.ALIAS }}
          key_password: ${{ secrets.KEY_PASSWORD}}
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/release/app-release.apk
  release:
    name: Release APK
    needs: apk
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: apk
          path: ./
      # Doku: https://github.com/actions/create-release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.1
          release_name: Release v1.0.1
          body: |
            - fix update of a route
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app-release.apk
          asset_name: ClimbingDiary.apk
          asset_content_type: application/zip