name: CI
on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [ 29 ]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v2
        with:
          path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: build signed APK
        uses: victorbnl/build-signed-apk@main
        with:
          keystore: ${{ secrets.SIGNING_KEY }}
          keystore_password: ${{ secrets.KEY_STORE_PASSWORD }}
          key_alias: ${{ secrets.ALIAS }}
          key_password: ${{ secrets.KEY_PASSWORD}}
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/release/app-release.apk
  test:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run unit tests
        run: ./gradlew test --stacktrace

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          profile: Nexus 6
          script: ./gradlew connectedCheck
  release:
    name: Release APK
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: apk
          path: ./
      # Doku: https://github.com/actions/create-release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.34
          release_name: Release v1.0.34
          body: |
            - fix Update Route and Project Bug
            - add animation if you tick a route :smile:
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app-release.apk
          asset_name: ClimbingDiary.apk
          asset_content_type: application/zip